### ISSUE TITLE
Its not working

### ISSUE THREAD

**Issue by xerodragon72** [CalderWhite/nullG#14]
Simply put its not working for windows

**Comment by CalderWhite** [comment]
I'd like to advise you not to use such absolute language, since it is, in fact working for certain windows environments. I'd need more information to debug and fix. (i.e. stack-trace, os, jdk version, jre)

**Comment by xerodragon72** [comment]
funny, anyways I'm using java runtime enviroment 8u144 on windows 64x or just simply the lastest build and when running the application an error occurs would you like a full error code?

**Comment by xerodragon72** [comment]
Never mind... The problem was that you require a development build of java, as javac.exe is not included in just the simple java. Maybe you should consider making a per-compiled branch or a Readme with a note about this issue
