### ISSUE TITLE
Javac unable to find file main.java

### ISSUE THREAD

**Issue by xerodragon72** [CalderWhite/nullG#15]
This is a problem with the startgame.bat

command prompt output
`
C:\Users\fengc>javac -cp ".;./*" -sourcepath ../src -d . ../src/nullG/Main.java
javac: file not found: ..\src\nullG\Main.java
Usage: javac <options> <source files>
use -help for a list of possible options
`

**Comment by xerodragon72** [comment]
in startgame.bat the command is

> javac -cp ".;./*" -sourcepath ../src -d . ../src/nullG/Main.java

however it should be:

` javac -cp ".;./*" -sourcepath ../src -d . /src/nullG/Main.java `

**Comment by CalderWhite** [comment]
@xerodragon72, please note that `startgame` is meant to be run in the base directory of the project.
