### ISSUE TITLE
Missing symbols

### ISSUE THREAD

**Issue by xerodragon72** [CalderWhite/nullG#16]
Full Command Prompt output:
> src\nullG\Main.java:13: error: cannot find symbol
        public Graphics graphics;
               ^
  symbol:   class Graphics
  location: class NullG
src\nullG\Main.java:14: error: cannot find symbol
        public Player player;
               ^
  symbol:   class Player
  location: class NullG
src\nullG\Main.java:15: error: cannot find symbol
        public static Utils utils;
                      ^
  symbol:   class Utils
  location: class NullG
src\nullG\Main.java:16: error: cannot find symbol
        public Events events;
               ^
  symbol:   class Events
  location: class NullG
src\nullG\Main.java:18: error: cannot find symbol
        public Stage currentStage = null;
               ^
  symbol:   class Stage
  location: class NullG
src\nullG\Main.java:34: error: cannot find symbol
                utils = new Utils(this);
                            ^
  symbol:   class Utils
  location: class NullG
src\nullG\Main.java:35: error: cannot find symbol
                graphics = new Graphics(this,width,height);
                               ^
  symbol:   class Graphics
  location: class NullG
src\nullG\Main.java:36: error: cannot find symbol
                player = new Player(this,0,0,Defaults.playerChar);
                             ^
  symbol:   class Player
  location: class NullG
src\nullG\Main.java:36: error: cannot find symbol
                player = new Player(this,0,0,Defaults.playerChar);
                                             ^
  symbol:   variable Defaults
  location: class NullG
src\nullG\Main.java:37: error: cannot find symbol
                events = new Events(this);
                             ^
  symbol:   class Events
  location: class NullG
src\nullG\Main.java:46: error: cannot find symbol
                currentStage = new Stage(this);
                                   ^
  symbol:   class Stage
  location: class NullG
src\nullG\Main.java:68: error: cannot find symbol
                                        case Defaults.charEXIT:
                                             ^
  symbol:   variable Defaults
  location: class NullG
src\nullG\Main.java:71: error: cannot find symbol
                                        case Defaults.charUP:
                                             ^
  symbol:   variable Defaults
  location: class NullG
src\nullG\Main.java:74: error: cannot find symbol
                                        case Defaults.charDOWN:
                                             ^
  symbol:   variable Defaults
  location: class NullG
src\nullG\Main.java:77: error: cannot find symbol
                                        case Defaults.charLEFT:
                                             ^
  symbol:   variable Defaults
  location: class NullG
src\nullG\Main.java:80: error: cannot find symbol
                                        case Defaults.charRIGHT:
                                             ^
  symbol:   variable Defaults
  location: class NullG
16 errors

Funny enough its the same error your targeting for windows is all messed up and the targets aren't working properly

**Comment by xerodragon72** [comment]
Please note, I don't program in java however I can only assume that that is the problem

**Comment by CalderWhite** [comment]
Is this a development problem? Going off "I don't program in java", I can only assume you're only trying to run the game. In that case, the class files are already compiled in the bin folder. On windows, you simply need to run (from the base working directory) `cd classes` and then `java -cp ".;./*" nullG.Main`. Also note, all development was done on java 8

**Comment by xerodragon72** [comment]
I highly recommend adding a readme

**Comment by xerodragon72** [comment]
After running command java -cp ".;./*" nullG.Main
```
java.io.FileNotFoundException: .\nullGData\home.stage (The system cannot find the path specified)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileReader.<init>(Unknown Source)
        at nullG.Stage.loadFile(Stage.java:26)
        at nullG.NullG.run(Main.java:48)
        at nullG.Main.main(Main.java:138)
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0
        at nullG.Stage.loadFile(Stage.java:50)
        at nullG.NullG.run(Main.java:48)
        at nullG.Main.main(Main.java:138)
```

**Comment by xerodragon72** [comment]
again a targeting issue

**Comment by CalderWhite** [comment]
Good Catch, @xerodragon72  ! Thanks for providing more info this time. I've updated the windows batch file to math the linux bash (sorry, I test on linux. I'll remember to keep the other updated in the future). The code was made to run in the root directory, however the batch script was outdated.
